FROM golang:1.15.6

# Linters

RUN GO111MODULE=on go get honnef.co/go/tools/cmd/staticcheck@2020.2
RUN curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b ${GOPATH}/bin v1.33.0

# Set our entrypoint to close after 28 minutes, and forcefully close at 30 minutes.
# This is to prevent Jenkins collecting cats.

ENTRYPOINT ["timeout", "-k30m", "28m"]
