// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/metadata.proto

package proto

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type InvokeMetadata struct {
	Version              uint32            `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Data                 map[string]string `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InvokeMetadata) Reset()         { *m = InvokeMetadata{} }
func (m *InvokeMetadata) String() string { return proto.CompactTextString(m) }
func (*InvokeMetadata) ProtoMessage()    {}
func (*InvokeMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_4891c0dff9aa45c8, []int{0}
}
func (m *InvokeMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeMetadata.Unmarshal(m, b)
}
func (m *InvokeMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeMetadata.Marshal(b, m, deterministic)
}
func (m *InvokeMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeMetadata.Merge(m, src)
}
func (m *InvokeMetadata) XXX_Size() int {
	return xxx_messageInfo_InvokeMetadata.Size(m)
}
func (m *InvokeMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeMetadata proto.InternalMessageInfo

func (m *InvokeMetadata) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *InvokeMetadata) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*InvokeMetadata)(nil), "metadata.InvokeMetadata")
	proto.RegisterMapType((map[string]string)(nil), "metadata.InvokeMetadata.DataEntry")
}

func init() { proto.RegisterFile("proto/metadata.proto", fileDescriptor_4891c0dff9aa45c8) }

var fileDescriptor_4891c0dff9aa45c8 = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x4d, 0x2d, 0x49, 0x4c, 0x49, 0x2c, 0x49, 0xd4, 0x03, 0x73, 0x85, 0x38, 0x60,
	0x7c, 0xa5, 0xd9, 0x8c, 0x5c, 0x7c, 0x9e, 0x79, 0x65, 0xf9, 0xd9, 0xa9, 0xbe, 0x50, 0x21, 0x21,
	0x09, 0x2e, 0xf6, 0xb2, 0xd4, 0xa2, 0xe2, 0xcc, 0xfc, 0x3c, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xde,
	0x20, 0x18, 0x57, 0xc8, 0x8c, 0x8b, 0x05, 0xa4, 0x42, 0x82, 0x49, 0x81, 0x59, 0x83, 0xdb, 0x48,
	0x49, 0x0f, 0x6e, 0x2a, 0xaa, 0x09, 0x7a, 0x2e, 0x89, 0x25, 0x89, 0xae, 0x79, 0x25, 0x45, 0x95,
	0x41, 0x60, 0xf5, 0x52, 0xe6, 0x5c, 0x9c, 0x70, 0x21, 0x21, 0x01, 0x2e, 0xe6, 0xec, 0xd4, 0x4a,
	0xb0, 0xd1, 0x9c, 0x41, 0x20, 0xa6, 0x90, 0x08, 0x17, 0x6b, 0x59, 0x62, 0x4e, 0x69, 0xaa, 0x04,
	0x13, 0x58, 0x0c, 0xc2, 0xb1, 0x62, 0xb2, 0x60, 0x74, 0x62, 0x8f, 0x62, 0x05, 0x3b, 0x38, 0x89,
	0x0d, 0x4c, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x21, 0xb6, 0x4e, 0xe1, 0xcf, 0x00, 0x00,
	0x00,
}
