// Code generated by "stringer -type=PacketKind -trimprefix=PacketKind_ -output=Packet_string.go"; DO NOT EDIT.

package drpcwire

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PacketKind_Reserved-0]
	_ = x[PacketKind_Invoke-1]
	_ = x[PacketKind_Message-2]
	_ = x[PacketKind_Error-3]
	_ = x[PacketKind_Cancel-4]
	_ = x[PacketKind_Close-5]
	_ = x[PacketKind_CloseSend-6]
	_ = x[PacketKind_Largest-7]
}

const _PacketKind_name = "ReservedInvokeMessageErrorCancelCloseCloseSendLargest"

var _PacketKind_index = [...]uint8{0, 8, 14, 21, 26, 32, 37, 46, 53}

func (i PacketKind) String() string {
	if i >= PacketKind(len(_PacketKind_index)-1) {
		return "PacketKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PacketKind_name[_PacketKind_index[i]:_PacketKind_index[i+1]]
}
