// Code generated by "stringer -type=Kind -trimprefix=Kind_ -output=packet_string.go"; DO NOT EDIT.

package drpcwire

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Kind_Reserved-0]
	_ = x[Kind_Invoke-1]
	_ = x[Kind_Message-2]
	_ = x[Kind_Error-3]
	_ = x[Kind_Cancel-4]
	_ = x[Kind_Close-5]
	_ = x[Kind_CloseSend-6]
	_ = x[Kind_Largest-7]
}

const _Kind_name = "ReservedInvokeMessageErrorCancelCloseCloseSendLargest"

var _Kind_index = [...]uint8{0, 8, 14, 21, 26, 32, 37, 46, 53}

func (i Kind) String() string {
	if i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
