// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: metadata.proto

package invoke

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type InvokeMetadata struct {
	Data                 map[string]string `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InvokeMetadata) Reset()         { *m = InvokeMetadata{} }
func (m *InvokeMetadata) String() string { return proto.CompactTextString(m) }
func (*InvokeMetadata) ProtoMessage()    {}
func (*InvokeMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{0}
}
func (m *InvokeMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeMetadata.Unmarshal(m, b)
}
func (m *InvokeMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeMetadata.Marshal(b, m, deterministic)
}
func (m *InvokeMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeMetadata.Merge(m, src)
}
func (m *InvokeMetadata) XXX_Size() int {
	return xxx_messageInfo_InvokeMetadata.Size(m)
}
func (m *InvokeMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeMetadata proto.InternalMessageInfo

func (m *InvokeMetadata) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*InvokeMetadata)(nil), "metadata.InvokeMetadata")
	proto.RegisterMapType((map[string]string)(nil), "metadata.InvokeMetadata.DataEntry")
}

func init() { proto.RegisterFile("metadata.proto", fileDescriptor_56d9f74966f40d04) }

var fileDescriptor_56d9f74966f40d04 = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4d, 0x2d, 0x49,
	0x4c, 0x49, 0x2c, 0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0x1a,
	0x19, 0xb9, 0xf8, 0x3c, 0xf3, 0xca, 0xf2, 0xb3, 0x53, 0x7d, 0xa1, 0x42, 0x42, 0x66, 0x5c, 0x2c,
	0x20, 0x5a, 0x82, 0x49, 0x81, 0x59, 0x83, 0xdb, 0x48, 0x49, 0x0f, 0xae, 0x17, 0x55, 0x9d, 0x9e,
	0x4b, 0x62, 0x49, 0xa2, 0x6b, 0x5e, 0x49, 0x51, 0x65, 0x10, 0x58, 0xbd, 0x94, 0x39, 0x17, 0x27,
	0x5c, 0x48, 0x48, 0x80, 0x8b, 0x39, 0x3b, 0xb5, 0x52, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08,
	0xc4, 0x14, 0x12, 0xe1, 0x62, 0x2d, 0x4b, 0xcc, 0x29, 0x4d, 0x95, 0x60, 0x02, 0x8b, 0x41, 0x38,
	0x56, 0x4c, 0x16, 0x8c, 0x4e, 0x1c, 0x51, 0x6c, 0x99, 0x60, 0xa3, 0x93, 0xd8, 0xc0, 0xce, 0x33,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x40, 0xd8, 0x39, 0x20, 0xb0, 0x00, 0x00, 0x00,
}
