// Code generated by a human. DO NOT EDIT.
// While this is not generated code, it contains stubs that match some generated code.
// Linters not treating this like generated code causes them to be very unhappy.

// Copyright (C) 2021 Storj Labs, Inc.
// See LICENSE for copying information.

// Package servicedefs contains empty stubs so that backcompat can compile.
package servicedefs

import (
	"context"
)

func NewDRPCServiceClient(_ interface{}) DRPCServiceClient { return nil }

func DRPCRegisterService(_, _ interface{}) error { return nil }

type In struct{ In int64 }
type Out struct{ Out int64 }

type DRPCServiceClient interface {
	Method1(ctx context.Context, in *In) (*Out, error)
	Method2(ctx context.Context) (DRPCService_Method2Client, error)
	Method3(ctx context.Context, in *In) (DRPCService_Method3Client, error)
	Method4(ctx context.Context) (DRPCService_Method4Client, error)
}

type DRPCService_Method2Client interface {
	Send(*In) error
	CloseAndRecv() (*Out, error)
}

type DRPCService_Method3Client interface {
	Recv() (*Out, error)
}

type DRPCService_Method4Client interface {
	Send(*In) error
	Recv() (*Out, error)
	CloseSend() error
}

type DRPCServiceServer interface {
	Method1(context.Context, *In) (*Out, error)
	Method2(DRPCService_Method2Stream) error
	Method3(*In, DRPCService_Method3Stream) error
	Method4(DRPCService_Method4Stream) error
}

type DRPCService_Method2Stream interface {
	SendAndClose(*Out) error
	Recv() (*In, error)
}

type DRPCService_Method3Stream interface {
	Send(*Out) error
}

type DRPCService_Method4Stream interface {
	Send(*Out) error
	Recv() (*In, error)
}
