// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: servicedefs.proto

package servicedefs

import (
	context "context"
	errors "errors"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
	drpc "storj.io/drpc"
	drpcerr "storj.io/drpc/drpcerr"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type In struct {
	In                   int64    `protobuf:"varint,1,opt,name=in,proto3" json:"in,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In) Reset()         { *m = In{} }
func (m *In) String() string { return proto.CompactTextString(m) }
func (*In) ProtoMessage()    {}
func (*In) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b01b08ac87a50d, []int{0}
}
func (m *In) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In.Unmarshal(m, b)
}
func (m *In) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In.Marshal(b, m, deterministic)
}
func (m *In) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In.Merge(m, src)
}
func (m *In) XXX_Size() int {
	return xxx_messageInfo_In.Size(m)
}
func (m *In) XXX_DiscardUnknown() {
	xxx_messageInfo_In.DiscardUnknown(m)
}

var xxx_messageInfo_In proto.InternalMessageInfo

func (m *In) GetIn() int64 {
	if m != nil {
		return m.In
	}
	return 0
}

type Out struct {
	Out                  int64    `protobuf:"varint,1,opt,name=out,proto3" json:"out,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Out) Reset()         { *m = Out{} }
func (m *Out) String() string { return proto.CompactTextString(m) }
func (*Out) ProtoMessage()    {}
func (*Out) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b01b08ac87a50d, []int{1}
}
func (m *Out) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out.Unmarshal(m, b)
}
func (m *Out) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out.Marshal(b, m, deterministic)
}
func (m *Out) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out.Merge(m, src)
}
func (m *Out) XXX_Size() int {
	return xxx_messageInfo_Out.Size(m)
}
func (m *Out) XXX_DiscardUnknown() {
	xxx_messageInfo_Out.DiscardUnknown(m)
}

var xxx_messageInfo_Out proto.InternalMessageInfo

func (m *Out) GetOut() int64 {
	if m != nil {
		return m.Out
	}
	return 0
}

func init() {
	proto.RegisterType((*In)(nil), "servicedefs.In")
	proto.RegisterType((*Out)(nil), "servicedefs.Out")
}

func init() { proto.RegisterFile("servicedefs.proto", fileDescriptor_37b01b08ac87a50d) }

var fileDescriptor_37b01b08ac87a50d = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x4d, 0x49, 0x4d, 0x2b, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x46,
	0x12, 0x52, 0x12, 0xe1, 0x62, 0xf2, 0xcc, 0x13, 0xe2, 0xe3, 0x62, 0xca, 0xcc, 0x93, 0x60, 0x54,
	0x60, 0xd4, 0x60, 0x0e, 0x62, 0xca, 0xcc, 0x53, 0x12, 0xe7, 0x62, 0xf6, 0x2f, 0x2d, 0x11, 0x12,
	0xe0, 0x62, 0xce, 0x2f, 0x2d, 0x81, 0x8a, 0x83, 0x98, 0x46, 0x27, 0x19, 0xb9, 0xd8, 0x83, 0x21,
	0xda, 0x85, 0x74, 0xb8, 0xd8, 0x7d, 0x53, 0x4b, 0x32, 0xf2, 0x53, 0x0c, 0x85, 0xf8, 0xf5, 0x90,
	0xad, 0xf1, 0xcc, 0x93, 0x12, 0x40, 0x11, 0x00, 0x99, 0xa5, 0x07, 0x53, 0x6d, 0x44, 0x84, 0x6a,
	0x0d, 0x46, 0x84, 0x7a, 0x63, 0x22, 0xd4, 0x1b, 0x30, 0x0a, 0x19, 0xc0, 0xd4, 0x9b, 0x10, 0x65,
	0xbe, 0x01, 0xa3, 0x93, 0x7e, 0x94, 0x6e, 0x71, 0x49, 0x7e, 0x51, 0x96, 0x5e, 0x66, 0xbe, 0x7e,
	0x4a, 0x51, 0x41, 0xb2, 0x7e, 0x66, 0x5e, 0x49, 0x6a, 0x51, 0x5e, 0x62, 0x8e, 0x7e, 0x52, 0x62,
	0x72, 0x76, 0x72, 0x7e, 0x6e, 0x41, 0x62, 0x89, 0x3e, 0x92, 0xc6, 0x24, 0x36, 0x70, 0xf8, 0x19,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xed, 0x52, 0xfd, 0x72, 0x54, 0x01, 0x00, 0x00,
}

// --- DRPC BEGIN ---

type DRPCServiceClient interface {
	DRPCConn() drpc.Conn

	Method1(ctx context.Context, in *In) (*Out, error)
	Method2(ctx context.Context) (DRPCService_Method2Client, error)
	Method3(ctx context.Context, in *In) (DRPCService_Method3Client, error)
	Method4(ctx context.Context) (DRPCService_Method4Client, error)
}

type drpcServiceClient struct {
	cc drpc.Conn
}

func NewDRPCServiceClient(cc drpc.Conn) DRPCServiceClient {
	return &drpcServiceClient{cc}
}

func (c *drpcServiceClient) DRPCConn() drpc.Conn { return c.cc }

func (c *drpcServiceClient) Method1(ctx context.Context, in *In) (*Out, error) {
	out := new(Out)
	err := c.cc.Invoke(ctx, "/servicedefs.Service/Method1", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drpcServiceClient) Method2(ctx context.Context) (DRPCService_Method2Client, error) {
	stream, err := c.cc.NewStream(ctx, "/servicedefs.Service/Method2")
	if err != nil {
		return nil, err
	}
	x := &drpcServiceMethod2Client{stream}
	return x, nil
}

type DRPCService_Method2Client interface {
	drpc.Stream
	Send(*In) error
	CloseAndRecv() (*Out, error)
}

type drpcServiceMethod2Client struct {
	drpc.Stream
}

func (x *drpcServiceMethod2Client) Send(m *In) error {
	return x.MsgSend(m)
}

func (x *drpcServiceMethod2Client) CloseAndRecv() (*Out, error) {
	if err := x.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Out)
	if err := x.MsgRecv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *drpcServiceClient) Method3(ctx context.Context, in *In) (DRPCService_Method3Client, error) {
	stream, err := c.cc.NewStream(ctx, "/servicedefs.Service/Method3")
	if err != nil {
		return nil, err
	}
	x := &drpcServiceMethod3Client{stream}
	if err := x.MsgSend(in); err != nil {
		return nil, err
	}
	if err := x.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DRPCService_Method3Client interface {
	drpc.Stream
	Recv() (*Out, error)
}

type drpcServiceMethod3Client struct {
	drpc.Stream
}

func (x *drpcServiceMethod3Client) Recv() (*Out, error) {
	m := new(Out)
	if err := x.MsgRecv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *drpcServiceClient) Method4(ctx context.Context) (DRPCService_Method4Client, error) {
	stream, err := c.cc.NewStream(ctx, "/servicedefs.Service/Method4")
	if err != nil {
		return nil, err
	}
	x := &drpcServiceMethod4Client{stream}
	return x, nil
}

type DRPCService_Method4Client interface {
	drpc.Stream
	Send(*In) error
	Recv() (*Out, error)
}

type drpcServiceMethod4Client struct {
	drpc.Stream
}

func (x *drpcServiceMethod4Client) Send(m *In) error {
	return x.MsgSend(m)
}

func (x *drpcServiceMethod4Client) Recv() (*Out, error) {
	m := new(Out)
	if err := x.MsgRecv(m); err != nil {
		return nil, err
	}
	return m, nil
}

type DRPCServiceServer interface {
	Method1(context.Context, *In) (*Out, error)
	Method2(DRPCService_Method2Stream) error
	Method3(*In, DRPCService_Method3Stream) error
	Method4(DRPCService_Method4Stream) error
}

type DRPCServiceUnimplementedServer struct{}

func (s *DRPCServiceUnimplementedServer) Method1(context.Context, *In) (*Out, error) {
	return nil, drpcerr.WithCode(errors.New("Unimplemented"), 12)
}

func (s *DRPCServiceUnimplementedServer) Method2(DRPCService_Method2Stream) error {
	return drpcerr.WithCode(errors.New("Unimplemented"), 12)
}

func (s *DRPCServiceUnimplementedServer) Method3(*In, DRPCService_Method3Stream) error {
	return drpcerr.WithCode(errors.New("Unimplemented"), 12)
}

func (s *DRPCServiceUnimplementedServer) Method4(DRPCService_Method4Stream) error {
	return drpcerr.WithCode(errors.New("Unimplemented"), 12)
}

type DRPCServiceDescription struct{}

func (DRPCServiceDescription) NumMethods() int { return 4 }

func (DRPCServiceDescription) Method(n int) (string, drpc.Receiver, interface{}, bool) {
	switch n {
	case 0:
		return "/servicedefs.Service/Method1",
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return srv.(DRPCServiceServer).
					Method1(
						ctx,
						in1.(*In),
					)
			}, DRPCServiceServer.Method1, true
	case 1:
		return "/servicedefs.Service/Method2",
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return nil, srv.(DRPCServiceServer).
					Method2(
						&drpcServiceMethod2Stream{in1.(drpc.Stream)},
					)
			}, DRPCServiceServer.Method2, true
	case 2:
		return "/servicedefs.Service/Method3",
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return nil, srv.(DRPCServiceServer).
					Method3(
						in1.(*In),
						&drpcServiceMethod3Stream{in2.(drpc.Stream)},
					)
			}, DRPCServiceServer.Method3, true
	case 3:
		return "/servicedefs.Service/Method4",
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return nil, srv.(DRPCServiceServer).
					Method4(
						&drpcServiceMethod4Stream{in1.(drpc.Stream)},
					)
			}, DRPCServiceServer.Method4, true
	default:
		return "", nil, nil, false
	}
}

func DRPCRegisterService(mux drpc.Mux, impl DRPCServiceServer) error {
	return mux.Register(impl, DRPCServiceDescription{})
}

type DRPCService_Method1Stream interface {
	drpc.Stream
	SendAndClose(*Out) error
}

type drpcServiceMethod1Stream struct {
	drpc.Stream
}

func (x *drpcServiceMethod1Stream) SendAndClose(m *Out) error {
	if err := x.MsgSend(m); err != nil {
		return err
	}
	return x.CloseSend()
}

type DRPCService_Method2Stream interface {
	drpc.Stream
	SendAndClose(*Out) error
	Recv() (*In, error)
}

type drpcServiceMethod2Stream struct {
	drpc.Stream
}

func (x *drpcServiceMethod2Stream) SendAndClose(m *Out) error {
	if err := x.MsgSend(m); err != nil {
		return err
	}
	return x.CloseSend()
}

func (x *drpcServiceMethod2Stream) Recv() (*In, error) {
	m := new(In)
	if err := x.MsgRecv(m); err != nil {
		return nil, err
	}
	return m, nil
}

type DRPCService_Method3Stream interface {
	drpc.Stream
	Send(*Out) error
}

type drpcServiceMethod3Stream struct {
	drpc.Stream
}

func (x *drpcServiceMethod3Stream) Send(m *Out) error {
	return x.MsgSend(m)
}

type DRPCService_Method4Stream interface {
	drpc.Stream
	Send(*Out) error
	Recv() (*In, error)
}

type drpcServiceMethod4Stream struct {
	drpc.Stream
}

func (x *drpcServiceMethod4Stream) Send(m *Out) error {
	return x.MsgSend(m)
}

func (x *drpcServiceMethod4Stream) Recv() (*In, error) {
	m := new(In)
	if err := x.MsgRecv(m); err != nil {
		return nil, err
	}
	return m, nil
}

// --- DRPC END ---
