// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: invoke.proto

package internal

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Invoke struct {
	Version              uint32            `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Invoke) Reset()         { *m = Invoke{} }
func (m *Invoke) String() string { return proto.CompactTextString(m) }
func (*Invoke) ProtoMessage()    {}
func (*Invoke) Descriptor() ([]byte, []int) {
	return fileDescriptor_2156226f9a4f30f8, []int{0}
}
func (m *Invoke) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Invoke.Unmarshal(m, b)
}
func (m *Invoke) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Invoke.Marshal(b, m, deterministic)
}
func (m *Invoke) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Invoke.Merge(m, src)
}
func (m *Invoke) XXX_Size() int {
	return xxx_messageInfo_Invoke.Size(m)
}
func (m *Invoke) XXX_DiscardUnknown() {
	xxx_messageInfo_Invoke.DiscardUnknown(m)
}

var xxx_messageInfo_Invoke proto.InternalMessageInfo

func (m *Invoke) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Invoke) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterType((*Invoke)(nil), "invoke.Invoke")
	proto.RegisterMapType((map[string]string)(nil), "invoke.Invoke.MetadataEntry")
}

func init() { proto.RegisterFile("invoke.proto", fileDescriptor_2156226f9a4f30f8) }

var fileDescriptor_2156226f9a4f30f8 = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0xcc, 0x2b, 0xcb,
	0xcf, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x66, 0x32, 0x72,
	0xb1, 0x79, 0x82, 0x99, 0x42, 0x12, 0x5c, 0xec, 0x65, 0xa9, 0x45, 0xc5, 0x99, 0xf9, 0x79, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0xbc, 0x41, 0x30, 0xae, 0x90, 0x05, 0x17, 0x47, 0x6e, 0x6a, 0x49, 0x62,
	0x4a, 0x62, 0x49, 0xa2, 0x04, 0x93, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0x8c, 0x1e, 0xd4, 0x34, 0x88,
	0x5e, 0x3d, 0x5f, 0xa8, 0xb4, 0x6b, 0x5e, 0x49, 0x51, 0x65, 0x10, 0x5c, 0xb5, 0x94, 0x35, 0x17,
	0x2f, 0x8a, 0x94, 0x90, 0x00, 0x17, 0x73, 0x76, 0x6a, 0x25, 0xd8, 0x02, 0xce, 0x20, 0x10, 0x53,
	0x48, 0x84, 0x8b, 0xb5, 0x2c, 0x31, 0xa7, 0x34, 0x55, 0x82, 0x09, 0x2c, 0x06, 0xe1, 0x58, 0x31,
	0x59, 0x30, 0x3a, 0x71, 0x45, 0x71, 0x64, 0xe6, 0x95, 0xa4, 0x16, 0xe5, 0x25, 0xe6, 0x24, 0xb1,
	0x81, 0x9d, 0x6d, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x95, 0x8e, 0x53, 0x19, 0xc6, 0x00, 0x00,
	0x00,
}
