// Code generated by hand. DO NOT EDIT.
//
// I lied. It's not generated, but we use names from generated code, and linting
// hates it. So, just pretend this is generated and everything will be fine.

// Copyright (C) 2021 Storj Labs, Inc.
// See LICENSE for copying information.

//go:build gogo && !custom
// +build gogo,!custom

package integration

import (
	"storj.io/drpc/internal/integration/gogoservice"
)

type (
	In  = service.In
	Out = service.Out

	DRPCServiceServer = service.DRPCServiceServer
	DRPCServiceClient = service.DRPCServiceClient

	DRPCService_Method2Stream = service.DRPCService_Method2Stream
	DRPCService_Method3Stream = service.DRPCService_Method3Stream
	DRPCService_Method4Stream = service.DRPCService_Method4Stream
)

var (
	NewDRPCServiceClient = service.NewDRPCServiceClient
	DRPCRegisterService  = service.DRPCRegisterService
	Equal                = service.Equal
	Encoding             = service.Encoding
)
